---
# tasks file for setup

- name: Create user
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/bash
    state: present
    # Assurez-vous que `home` et `groups` sont définis si nécessaires, par exemple :
    # home: /home/{{ user }}
    # groups: somegroup

- name: Ensure the user group exists
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: Add authorized key for the user
  ansible.builtin.authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600  # Optional: cache is valid for 1 hour

